FROM darthjee/circleci_taap:0.7.1 as base
FROM darthjee/scripts:0.1.8 as scripts

######################################

FROM base as builder

ADD source/Gemfile* /home/circleci/project/
ADD source/bower.json /home/circleci/project/

ENV HOME_DIR /home/circleci

COPY --chown=circleci:circleci --from=scripts /home/scripts/builder/bundle_builder.sh /usr/local/sbin/bundle_builder.sh
RUN /bin/bash bundle_builder.sh

COPY --chown=circleci:circleci --from=scripts /home/scripts/builder/bower_builder.sh /usr/local/sbin/bower_builder.sh
RUN /bin/bash bower_builder.sh

#######################
#FINAL IMAGE
FROM base

USER root

RUN apt-get install telnet

COPY --chown=circleci:circleci --from=builder /home/circleci/bundle/ /usr/local/bundle/
COPY --chown=circleci:circleci --from=builder /home/circleci/bower/ /home/circleci/.cache/bower/

USER circleci
