FROM httpd:2.4.48

RUN apt-get update
RUN apt-get install -y openssh-server

RUN mkdir /usr/local/apache2/htdocs/test \
  /usr/local/apache2/htdocs/app \
  /run/sshd

COPY httpd/sshd_config /etc/ssh/sshd_config

COPY httpd/entrypoint.sh /entrypoint.sh
CMD ["/entrypoint.sh"]
