require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'db/**/*.rb'
    - 'spec/**/*_spec.rb'
    - 'spec/support/**/*.rb'

Style/MixinUsage:
  Exclude:
    - 'bin/*'

Layout/LineLength:
  Exclude:
    - 'db/schema.rb'
    - 'spec/spec_helper.rb'
    - 'config/environments/*.rb'
    - 'config/initializers/content_security_policy.rb'

Style/WordArray:
  Exclude:
    - 'db/schema.rb'

Style/StringLiterals:
  Exclude:
    - 'db/schema.rb'

Style/FrozenStringLiteralComment:
  Exclude:
    - 'db/schema.rb'

Style/NumericLiterals:
  Exclude:
    - 'db/schema.rb'

Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - 'db/schema.rb'

RSpec/NestedGroups:
  Max: 4

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
