# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.3.1'

gem 'importmap-rails'
gem 'jbuilder'
gem 'mysql2'
gem 'observer'
gem 'puma', '~> 6.4.3'
gem 'rails', '~> 7.2.x'
gem 'sidekiq', '~> 7.0'
gem 'sprockets-rails'
gem 'stimulus-rails'
gem 'turbo-rails'

gem 'bootsnap', require: false
gem 'globalid', '>= 1.1.0'
gem 'rack', '>= 2.2.6.3'
gem 'sassc-rails', '>= 2.1.2'
gem 'tzinfo-data'
gem 'uglifier', '4.2.0'

gem 'arstotzka', '1.6.2'
gem 'azeroth', '>= 2.1.1'
gem 'danica', '3.0.0'
gem 'darthjee-active_ext', '>= 1.3.2'
gem 'darthjee-core_ext', '>= 3.0.0'
gem 'docile', '>= 1.4.1'
gem 'gnuplot', '2.6.2'
gem 'kiroshi', '0.3.1'
gem 'magicka', '~> 1.1.0'
gem 'matrix', '0.4.3'
gem 'nokogiri', '1.18.8'
gem 'sinclair', '3.0.1'
gem 'tarquinn', '~> 0.3.0'
gem 'zyra', '1.2.0'

group :development, :test do
  gem 'factory_bot',        '6.2.1'
  gem 'pry',                '>= 0.14.2'
  gem 'pry-nav',            '>= 1.0.0'
  gem 'pry-rails',          '>= 0.3.9'
  gem 'reek',               '>= 6.4.0'
  gem 'rspec',              '>= 3.13.0'
  gem 'rspec-core',         '>= 3.13.3'
  gem 'rspec-expectations', '>= 3.13.3'
  gem 'rspec-mocks',        '>= 3.13.2'
  gem 'rspec-rails',        '>= 8.0.0'
  gem 'rspec-support',      '>= 3.13.2'
  gem 'rubocop',            '>= 1.75.5'
  gem 'rubocop-rspec',      '>= 3.6.0'
  gem 'rubycritic',         '>= 4.9.2'
  gem 'shoulda-matchers',   '5.3.0'
  gem 'simplecov',          '0.22.0'
  gem 'timecop',            '0.9.6'
  gem 'yard',               '0.9.37'
  gem 'yardstick',          '0.9.9'
  gem 'zonebie',            '0.6.1'

  gem 'rails-controller-testing', '1.0.5'
end

group :development do
  gem 'web-console', '4.2.0'
end

group :test do
  gem 'database_cleaner', '2.0.2'
  gem 'webmock',          '3.18.1'

  gem 'rspec-collection_matchers', '1.2.1'
end
